# Run a couple of linters on code in repo
# * shellcheck for shell scripts
# * YAPF for Python scripts
name: Lint checks
on: [push, pull_request]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      uses: bewuethr/shellcheck-action@v1
  yapf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: yapf
      uses: AlexanderMelde/yapf-action@master
